tidevice perf 优化
alibaba/taobao-iphone-device pull request #122
Opened 2021-07-22 07:18 UTC by huang1988519

**修复**：`iter_opengl_data` 回调 `_reply_null` 导致的 `OSError: [Errno 22] Invalid argument`。修复后多个小时测试，运行正常。

**功能**：tidevice perf 支持过滤 `cpu/fps/memory/network/screenshot`, 减少不必要开销。
**优化**：tidevice perf 目标程序未启动时仍然输出 cpu 数据，并新增 cpu 核数，系统cpu 数据。value 值去除百分比计算，直接输入数值，方便外部加工。

2021-07-22 07:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/taobao-iphone-device?pullRequest=122) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/taobao-iphone-device?pullRequest=122) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/taobao-iphone-device?pullRequest=122) it.</sub>

2021-08-11 07:14 UTC, codeskyblue requested changes
感谢pr，还希望做调整。重要的是那个cpuUsage计算方法，麻烦给备注一下原因

2021-08-11 07:14 UTC, codeskyblue commented on tidevice/_perf.py
> +        # cpu_usage *= cpu_total_load
这里我不是太懂，为什么要把下面的方法去掉。
因为之前测试的时候会有cpuUsage计算过大的问题

2021-08-11 07:14 UTC, codeskyblue commented on tidevice/__main__.py
> +                dict(args=['-P', '--perfs'], help='cpu,memory,fps,network,screenshot. separate by ","', required=False),],
参考ps -o cpu,mem 你这个也改成 -o 好了

2021-08-11 07:21 UTC, huang1988519 commented on tidevice/_perf.py
> +        # cpu_usage *= cpu_total_load
我理解之前逻辑这么写的逻辑是为了得到 cpu 使用 百分比。 但是 xcode 真实调试过程中会根据 cpu 核数

2021-08-11 07:37 UTC, huang1988519 commented on tidevice/__main__.py
> +                dict(args=['-P', '--perfs'], help='cpu,memory,fps,network,screenshot. separate by ","', required=False),],
好的，跟上边问题确认后一并修改。

2021-08-12 03:29 UTC, merged

2021-08-12 03:30 UTC, codeskyblue commented
我先手工合并了，-perfs我改成了-o

2021-08-12 03:36 UTC, huang1988519 commented
> 我先手工合并了，-perfs我改成了-o

学习了，多谢大佬，修复了 None 判断和类型转换